[project]
name = "compa-warehouse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dagster>=1.13.18",
    "dagster-dbt>=0.29.18",
    "dagster-webserver>=1.13.18",
    "db-dtypes>=1.7.1",
    "dbt-bigquery>=1.12.0",
    "dbt-duckdb>=1.11.0",
    "dlt[bigquery,duckdb]>=1.29.1",
    "duckdb>=1.5.5",
    "google-api-python-client>=2.200.0",
    "openpyxl>=3.1.5",
    "pandas>=3.0.5",
    "pyarrow>=25.0.1",
    "python-dotenv>=1.2.2",
    "streamlit>=1.59.1",
    "xlrd>=2.0.2",
]
